/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arenasessence2;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Formatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author hectorledez el gamer
 */
public class Podologia extends javax.swing.JFrame {

    /**
     * Creates new form Podologia
     */
    public Podologia() {
        initComponents();
        jLabel15.setText(hoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PodoPanel = new javax.swing.JPanel();
        InflaIZQ = new javax.swing.JTextField();
        OtroIZQ = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        HTA = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        DM = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        Cardiopatia = new javax.swing.JTextField();
        HidratacionDER = new javax.swing.JTextField();
        Marcapasos = new javax.swing.JTextField();
        ColorDER = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Otros = new javax.swing.JTextArea();
        OlorDER = new javax.swing.JTextField();
        TempDER = new javax.swing.JTextField();
        DolorDER = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        InflaDER = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        OtroDER = new javax.swing.JTextField();
        LimMovilidad = new javax.swing.JCheckBox();
        HidratacionIZQ = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        ColorIZQ = new javax.swing.JTextField();
        Pulsopedido = new javax.swing.JCheckBox();
        OlorIZQ = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        TempIZQ = new javax.swing.JTextField();
        Sensivilidad = new javax.swing.JCheckBox();
        DolorIZQ = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        AsepDER = new javax.swing.JTextField();
        LimpIZQ = new javax.swing.JTextField();
        OnicIZQ = new javax.swing.JTextField();
        OnicDER = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        ResecDER = new javax.swing.JTextField();
        DespiIZQ = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        DesuIZQ = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        AsepIZQ = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        LimpDER = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        ResecIZQ = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        DespiDER = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        DesuDER = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        ResecheIZQ = new javax.swing.JTextField();
        LimpdigIZQ = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        AsepfinIZQ = new javax.swing.JTextField();
        MaspodIZQ = new javax.swing.JTextField();
        OtroTraIZQ = new javax.swing.JTextField();
        OtroTraDER = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        ResechipIZQ = new javax.swing.JTextField();
        ResechipDER = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        MaspodDER = new javax.swing.JTextField();
        AsepfinDER = new javax.swing.JTextField();
        ResecheDER = new javax.swing.JTextField();
        LimpdigDER = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        PatoIZQ = new javax.swing.JTextField();
        PatoDER = new javax.swing.JTextField();
        jLabel82 = new javax.swing.JLabel();
        Lavpies = new javax.swing.JCheckBox();
        jLabel83 = new javax.swing.JLabel();
        Buensec = new javax.swing.JCheckBox();
        Calzado = new javax.swing.JCheckBox();
        Calcetines = new javax.swing.JCheckBox();
        Autoexamen = new javax.swing.JCheckBox();
        Controldiab = new javax.swing.JCheckBox();
        Descalzo = new javax.swing.JCheckBox();
        Chequeos = new javax.swing.JCheckBox();
        Watero = new javax.swing.JCheckBox();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        Direc = new javax.swing.JTextField();
        corre = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        Fnaci = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Finalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Anamnesis Podologia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(315, 315, 315))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel39.setText("Pie derecho");

        jLabel44.setText("Hidratacion");

        jLabel45.setText("HTA");

        jLabel46.setText("Color");

        jLabel47.setText("DM");

        jLabel48.setText("Olor");

        jLabel49.setText("Cardiopatia");

        jLabel50.setText("Temperatura");

        jLabel51.setText("Marcapasos");

        jLabel52.setText("Dolor");

        jLabel53.setText("Signos de inflamacion");

        DM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMActionPerformed(evt);
            }
        });

        jLabel54.setText("Otros");

        Cardiopatia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardiopatiaActionPerformed(evt);
            }
        });

        Marcapasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcapasosActionPerformed(evt);
            }
        });

        jLabel55.setText("Otros");

        Otros.setColumns(20);
        Otros.setLineWrap(true);
        Otros.setRows(4);
        Otros.setWrapStyleWord(true);
        jScrollPane3.setViewportView(Otros);

        jLabel56.setText("Examen Fisico");

        jLabel57.setText("Limitaciones de movilidad");

        LimMovilidad.setText("Si");

        jLabel58.setText("Pulso Pedio");

        Pulsopedido.setText("Presente");
        Pulsopedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulsopedidoActionPerformed(evt);
            }
        });

        jLabel59.setText("Sensibilidad");

        Sensivilidad.setText("Presente");

        jLabel60.setText("Evaluacion");

        jLabel61.setText("Pie izquierdo");

        jLabel62.setText("Antecedentes morbidos personales");

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Tratamiento Pologico");

        jLabel64.setText("Desvastado de uña");

        jLabel65.setText("P I");

        jLabel66.setText("Asepcia inicial");

        jLabel67.setText("P D");

        jLabel68.setText("Limpieza Surc");

        jLabel69.setText("Onicotomia");

        jLabel70.setText("Despiculacion");

        jLabel71.setText("Resecado");

        DesuDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesuDERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66)
                    .addComponent(jLabel68)
                    .addComponent(jLabel69)
                    .addComponent(jLabel70)
                    .addComponent(jLabel71)
                    .addComponent(jLabel64))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DesuIZQ)
                            .addComponent(ResecIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DespiIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OnicIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LimpIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AsepIZQ, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DesuDER)
                            .addComponent(ResecDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DespiDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OnicDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LimpDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AsepDER, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jLabel67))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsepIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsepDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimpIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnicIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnicDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DespiDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DespiIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel70))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResecIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResecDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71))
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesuDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DesuIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel72.setText("Mas poda");

        jLabel73.setText("Otros");

        jLabel74.setText("Asep. final");

        jLabel75.setText("Limp esp int digital");

        jLabel76.setText("Resec. helomas");

        jLabel77.setText("Resec. hiperquerat");

        jLabel78.setText("P I");

        jLabel79.setText("P D");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel74)
                            .addComponent(jLabel77)
                            .addComponent(jLabel76)
                            .addComponent(jLabel75)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73))
                        .addGap(153, 153, 153))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel78, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(OtroTraIZQ)
                                    .addComponent(MaspodIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AsepfinIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LimpdigIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResecheIZQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResechipIZQ, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39)))))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OtroTraDER)
                            .addComponent(MaspodDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AsepfinDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LimpdigDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResecheDER, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ResechipDER, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(jLabel78))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel77))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ResechipIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ResechipDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(ResecheIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResecheDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel75)
                    .addComponent(LimpdigIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpdigDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(AsepfinIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AsepfinDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(MaspodIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaspodDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel73)
                    .addComponent(OtroTraIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtroTraDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel80.setText("Patologias encontradas");

        jLabel81.setText("P I");

        jLabel82.setText("P D");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel80)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel81)
                        .addGap(423, 423, 423))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel82)
                        .addGap(18, 18, 18)
                        .addComponent(PatoDER))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(PatoIZQ)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel80)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel81)
                    .addComponent(PatoIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(PatoDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Lavpies.setText("Lavado diario de pies");

        jLabel83.setText("Evaluacion de autocuidado");

        Buensec.setText("Buen secado");

        Calzado.setText("Uso de calzado adecuado");

        Calcetines.setText("Uso adecuado de calcetines");

        Autoexamen.setText("Autoexamen de los pies");

        Controldiab.setText("Control Periodico de diabetico");

        Descalzo.setText("No camina descalzo");

        Chequeos.setText("Realiza chequeos periodicos");

        Watero.setText("No utiliza bolsa de agua caliente en los pies");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(177, 177, 177))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Autoexamen)
                    .addComponent(jLabel83)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lavpies)
                            .addComponent(Buensec)
                            .addComponent(Calzado)
                            .addComponent(Calcetines))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Watero)
                            .addComponent(Chequeos)
                            .addComponent(Descalzo)
                            .addComponent(Controldiab))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel63)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel83)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lavpies)
                    .addComponent(Controldiab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buensec)
                    .addComponent(Descalzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calzado)
                    .addComponent(Chequeos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcetines)
                    .addComponent(Watero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Autoexamen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel84.setText("Direccion");

        jLabel85.setText("Mail");

        jLabel86.setText("Ciudad");

        jLabel87.setText("Fecha de Nacimiento");

        Fnaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnaciActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Indicaciones de tratamiento ortopedico");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Separador de dedos de silicona");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Protector de dedo tipo dedal (silicona heloma distal)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Protector de dedo tubular (silicona) en caso de heloma dorsal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Talonera de silicona en caso de talalgia");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Crema micotica recomendada");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel8.setText("Yo");

        jLabel9.setText("Entiendo que las tecnicas de podologia, que se administran ");

        jLabel10.setText("aquí, tienen el proposito de aliviar el dolor al tener uñas largas, realizando corte y embellecimiento de pies. no es tarea");

        jLabel11.setText("del terapeuta diagnosticar afecciones enfermedades u otros transtornos  fisicos, como tal  el terapeuta no prescribe");

        jLabel12.setText("tratamientos medico alguno, se me ha dejado bien claro y se ha recomendado  que vea algun medico podologico clinico");

        jLabel13.setText("si sufro alguna dolencia.");

        jLabel14.setText("Fecha");

        jLabel15.setText("jLabel15");

        jLabel16.setText("Firma");

        jButton1.setText("Agregar firma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(248, 248, 248))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(7, 7, 7)))
                .addGap(106, 106, 106))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PodoPanelLayout = new javax.swing.GroupLayout(PodoPanel);
        PodoPanel.setLayout(PodoPanelLayout);
        PodoPanelLayout.setHorizontalGroup(
            PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PodoPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodoPanelLayout.createSequentialGroup()
                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(71, 71, 71)))
                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PodoPanelLayout.createSequentialGroup()
                                        .addComponent(LimMovilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(190, 190, 190))
                                    .addGroup(PodoPanelLayout.createSequentialGroup()
                                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Pulsopedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Sensivilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(65, 65, 65))))
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PodoPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(181, 181, 181))
                                    .addGroup(PodoPanelLayout.createSequentialGroup()
                                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(HidratacionDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(HidratacionIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(OlorDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OlorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(ColorDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ColorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(TempDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TempIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(DolorDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DolorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(InflaDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(InflaIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                                .addComponent(OtroDER, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(OtroIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(PodoPanelLayout.createSequentialGroup()
                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel62)
                            .addComponent(jLabel47)
                            .addComponent(jLabel49)
                            .addComponent(jLabel51)
                            .addComponent(jLabel55)
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(69, 69, 69))
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(135, 135, 135))
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(150, 150, 150))
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(125, 125, 125))
                            .addComponent(jLabel56)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46)
                            .addComponent(jLabel48)
                            .addComponent(jLabel50)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54))
                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PodoPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DM, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cardiopatia)
                                    .addComponent(Marcapasos)
                                    .addComponent(jScrollPane3)
                                    .addComponent(HTA, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(corre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(city)
                            .addComponent(Direc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fnaci, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        PodoPanelLayout.setVerticalGroup(
            PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PodoPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel84)
                    .addComponent(Direc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel85)
                    .addComponent(corre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel86)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87)
                    .addComponent(Fnaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(HTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(DM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(Cardiopatia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(Marcapasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(LimMovilidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PodoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PodoPanelLayout.createSequentialGroup()
                        .addComponent(Pulsopedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sensivilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(jLabel39))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(HidratacionDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HidratacionIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(ColorDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(OlorDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OlorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(TempDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TempIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(DolorDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DolorIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(InflaDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InflaIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PodoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(OtroDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OtroIZQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(PodoPanel);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        Finalizar.setText("Finalizar");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(378, 378, 378)
                        .addComponent(Finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Finalizar)
                    .addComponent(Volver))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean fincl = false;
String nombre;
String apellido;
String tel;
String edad;
String fecha;
String hora;

    public void Pase(String nombre, String apellido, String tel,String edad,String fecha,String hora){
        this.nombre = nombre;
        this.apellido = apellido;
        this.tel = tel;
        this.edad = edad;
        this.fecha = fecha;
        this.hora = hora;
    }
    public boolean isFincl() {
        return fincl;
    }
    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        this.fincl = true;
    }//GEN-LAST:event_VolverActionPerformed
    private String barra = File.separator;
    private String Ubicacion = System.getProperty("user.dir") + barra + "Podologia" + barra;
    String limo;
    String Pulso;
    String sen;
    String lavp;
    String sec;
    String calza;
    String calse;
    String auex;
    String cdia;
    String descal;
    String check;
    String bolcan;
    private String limov(boolean lm){
        if(lm == true){
            this.limo = "Si";
        }else{
            this.limo = "No";
        }
        return this.limo;
    }
    private String pul(boolean lm){
        if(lm == true){
            this.Pulso = "Presente";
        }else{
            this.Pulso = "Ausente";
        }
        return this.Pulso;
    }
    private String sensi(boolean lm){
        if(lm == true){
            this.sen = "Presente";
        }else{
            this.sen = "Ausente";
        }
        return this.sen;
    }
    private String lavp(boolean lm){
        if(lm == true){
            this.lavp = "Si";
        }else{
            this.lavp = "No";
        }
        return this.lavp;
    }
    private String sec(boolean lm){
        if(lm == true){
            this.sec = "Si";
        }else{
            this.sec = "No";
        }
        return this.sec;
    }
    
    private String calza(boolean lm){
        if(lm == true){
            this.calza = "Si";
        }else{
            this.calza = "No";
        }
        return this.calza;
    }
    
    private String calse(boolean lm){
        if(lm == true){
            this.calse = "Si";
        }else{
            this.calse = "No";
        }
        return this.calse;
    }
    private String auex(boolean lm){
        if(lm == true){
            this.auex = "Si";
        }else{
            this.auex = "No";
        }
        return this.auex;
    }
    
    private String cdia(boolean lm){
        if(lm == true){
            this.cdia = "Si";
        }else{
            this.cdia = "No";
        }
        return this.cdia;
    }
    
    private String descal(boolean lm){
        if(lm == true){
            this.descal = "Si";
        }else{
            this.descal = "No";
        }
        return this.descal;
    }
    
    private String check(boolean lm){
        if(lm == true){
            this.check = "Si";
        }else{
            this.check = "No";
        }
        return this.check;
    }
    
    private String bolcan(boolean lm){
        if(lm == true){
            this.bolcan = "Si";
        }else{
            this.bolcan = "No";
        }
        return this.bolcan;
    }
    boolean OK = false;
    
    
    private void reseteo(JPanel N1){
        for(Object o : N1.getComponents()){
            if(o instanceof JTextField){
                ((JTextField) o).setText("");
            }
        }
    }
    private void reseteobox(JPanel N1){
        for(Object o : N1.getComponents()){
            if(o instanceof JCheckBox){
                ((JCheckBox) o).setSelected(false);
            }
        }
    }
    private boolean Listo = false;
    LocalDate hoy0 = LocalDate.now();
    String hoy = hoy0.getDayOfMonth()+"/"+hoy0.getMonthValue()+"/"+hoy0.getYear();
    String imagenesGeneral = System.getProperty("user.dir")+barra+"Imagenes"+barra;
    String imagenesFir = imagenesGeneral+"FirmasPodolog"+barra;
    File imgF  = new File(imagenesFir);
    private void Crear() {
        LocalTime ora = LocalTime.now();
        String ubicacion2 = Ubicacion + nombre + barra;
        System.out.println(ubicacion2);
        String Archivo = hoy0+" "+ora.getHour()+"-"+ora.getMinute()+"-"+ora.getSecond()+".Podologia";
        File crea_Ubicacion = new File(ubicacion2);
        File crea_archivo = new File(ubicacion2 + Archivo);
        if (crea_archivo.exists()) {
            //JOptionPane.showMessageDialog(rootPane, "Por favor ingrese la fecha de hoy");
        } else {
            try {
                crea_Ubicacion.mkdirs();
                imgF.mkdirs();
                Formatter crea = new Formatter(ubicacion2 + Archivo);
                crea.format("%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s\r\n%s",
                        "Fecha=" + hoy,//1
                        "hora=" + ora,//2
                        "Nombre=" + nombre,
                        "Apellido=" + apellido,
                        "Telefono=" + tel,
                        "Edad=" + edad,
                        "Direcc"+Direc.getText(),
                        "Mail"+corre.getText(),
                        "Ciud"+city.getText(),
                        "Naci"+Fnaci.getText(),
                        "Fechadecita=" + fecha,
                        "Horadecita=" + hora,
                        "HTA="+HTA.getText(),//10
                        "DM="+DM.getText(),//11
                        "Cardiopatia="+Cardiopatia.getText(),//12
                        "Marcapasos="+Marcapasos.getText(),//13
                        "Otros="+Otros.getText(),//14
                        "LimMov="+limov(LimMovilidad.isSelected()),//15
                        "PulsoPedido="+pul(Pulsopedido.isSelected()),//16
                        "Sensivilidad="+sensi(Sensivilidad.isSelected()),//17
                        "HidratacionIZ="+HidratacionDER.getText(),"HidratacionDE="+HidratacionIZQ.getText(),//19
                        "ColorIZ="+ColorDER.getText(),"ColorDE="+ColorIZQ.getText(),//21
                        "OlorIZ="+OlorDER.getText(),"OlorDE="+OlorIZQ.getText(),//23
                        "TemIZ="+TempDER.getText(),"TemDE="+TempIZQ.getText(),//25
                        "DolorIZ="+DolorDER.getText(),"DolorDE="+DolorIZQ.getText(),//27
                        "InflamacionIZ="+InflaDER.getText(),"InflamacionDE="+InflaIZQ.getText(),//29
                        "OtroIZ="+OtroDER.getText(),"OtroDE="+OtroIZQ.getText(),//31
                        "AcepinIZ="+AsepIZQ.getText(),"AcepinDE="+AsepDER.getText(),//33
                        "LipiezaIZ="+LimpIZQ.getText(),"LimpiezaDE="+LimpDER.getText(),//35
                        "OnicotomiaIZ="+OnicIZQ.getText(),"OnicotomiaDE="+OnicDER.getText(),//37
                        "DespiculIZ="+DespiIZQ.getText(),"DespiculDE="+DespiDER.getText(),//39
                        "ResecadoIZ="+ResecIZQ.getText(),"ResecadoDE="+ResecDER.getText(),//41
                        "DesvuIZ="+DesuIZQ.getText(),"DesvuDE="+DesuDER.getText(),//43
                        "ResecadoHipIZ="+ResechipIZQ.getText(),"ResecadoHipDE="+ResechipDER.getText(),//45
                        "ResecadoHelIZ="+ResecheIZQ.getText(),"ResecadoHelDE="+ResecheDER.getText(),//47
                        "LimDigIZ="+LimpdigIZQ.getText(),"LimpDigDE="+LimpdigDER.getText(),//49
                        "AsepfinalIZ="+AsepfinIZQ.getText(),"AsepfinalDE="+AsepfinDER.getText(),//51
                        "MasPodIZ="+MaspodIZQ.getText(),"MasPodDE="+MaspodDER.getText(),//53
                        "OtrotraIZ="+OtroTraIZQ.getText(),"OtrotraDE="+OtroTraDER.getText(),//55
                        "PatoloIZ="+PatoIZQ.getText(),"PatolDE="+PatoDER.getText(),//57
                        "LavadoPies="+lavp(Lavpies.isSelected()),//58
                        "BuebSec="+sec(Buensec.isSelected()),//59
                        "Calsado="+calza(Calzado.isSelected()),//60
                        "Calset="+calse(Calcetines.isSelected()),//61
                        "Autoex="+auex(Autoexamen.isSelected()),//62
                        "Controdia="+cdia(Controldiab.isSelected()),//63
                        "Descal="+descal(Descalzo.isSelected()),//64
                        "Chequeo="+check(Chequeos.isSelected()),//65
                        "Blosa="+bolcan(Watero.isSelected()),
                        "Indi1="+jTextField3.getText(),
                        "Indi2="+jTextField2.getText(),
                        "Indi3="+jTextField1.getText(),
                        "Indi4="+jTextField4.getText(),
                        "Indi5="+jTextField5.getText(),
                        "urlFirma="+imgF.getPath()+barra+nombre+" "+apellido+".jpg");//66
                
                crea.close();
                this.Listo = true;
                this.OK = true;
                
                ImageIcon imageF = (ImageIcon) jLabel17.getIcon();
                BufferedImage IconoSagrado = new BufferedImage( imageF.getIconWidth(),
                                                                imageF.getIconHeight(),
                                                                BufferedImage.TYPE_INT_RGB);
                Graphics2D g2 = IconoSagrado.createGraphics();
                g2.drawImage(imageF.getImage(), 0, 0,imageF.getImageObserver());
                g2.dispose();
                ImageIO.write(IconoSagrado,"jpg",new File(imgF.getPath()+barra+nombre+" "+apellido+".jpg"));
                
                JOptionPane.showMessageDialog(rootPane, "Persona registrada");
                this.fincl = true;
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "E R R O R ! ! !");
                System.out.println(e);
            }
            
        }
    }

    public boolean isOK() {
        return OK;
    }
    
    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        // TODO add your handling code here:
        Crear();
        if(Listo == true){
            reseteo(PodoPanel);
            reseteobox(PodoPanel);
        }
    }//GEN-LAST:event_FinalizarActionPerformed

    private void DMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DMActionPerformed

    private void CardiopatiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardiopatiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardiopatiaActionPerformed

    private void MarcapasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcapasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcapasosActionPerformed

    private void PulsopedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulsopedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PulsopedidoActionPerformed

    private void DesuDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesuDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesuDERActionPerformed

    private void FnaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnaciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnaciActionPerformed

    String RutaIMG;
    File imgimpor;
    int anchres;
    int largres;
    ImageIcon imag = null;
    private void AgreFir(){
        JFileChooser PIMG = new JFileChooser();
        PIMG.showOpenDialog(this);
        File foto = PIMG.getSelectedFile();
        if(foto != null){
            if( foto.getName().contains(".jpg") || 
                foto.getName().contains(".png") ||
                foto.getName().contains(".jpeg") ||
                foto.getName().contains(".gif")){
                this.RutaIMG = foto.getPath();
                System.out.println(foto.getPath());
                ImageIcon imag1 = new ImageIcon(foto.getPath());
                int anchoO = jLabel17.getHeight();
                int largoO = jLabel17.getWidth();
                int ancho = imag1.getIconHeight();
                int largo = imag1.getIconWidth();
                if(ancho == largo){
                    this.anchres = largoO;
                    this.largres = largoO;
                }else{
                    if(ancho > anchoO){
                        this.anchres = ancho-(ancho-anchoO);
                    }
                    if(ancho < anchoO){
                        this.anchres = anchoO-(anchoO-ancho);
                    }
                    if(ancho == anchoO){
                        this.anchres = ancho;
                    }
                    if(largo > largoO){
                        this.largres = largo-(largo-largoO);
                    }
                    if(largo < largoO){
                        this.largres = largoO-(largoO-largo);
                    }
                }
                System.out.println(" --> "+anchres+"x"+largres);
                System.out.println(" --> "+anchoO+"x"+largoO);
                System.out.println(" --> "+ancho+"x"+largo);
                Image imag0 = new ImageIcon(foto.getPath()).getImage();
                this.imag = new ImageIcon(imag0.getScaledInstance(largres, anchres, Image.SCALE_SMOOTH));
                jLabel17.setIcon(imag);
                //foto.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar Archivos de imagen \n (JPG o PNG)");
            }
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgreFir();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Podologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Podologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Podologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Podologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Podologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AsepDER;
    private javax.swing.JTextField AsepIZQ;
    private javax.swing.JTextField AsepfinDER;
    private javax.swing.JTextField AsepfinIZQ;
    private javax.swing.JCheckBox Autoexamen;
    private javax.swing.JCheckBox Buensec;
    private javax.swing.JCheckBox Calcetines;
    private javax.swing.JCheckBox Calzado;
    private javax.swing.JTextField Cardiopatia;
    private javax.swing.JCheckBox Chequeos;
    private javax.swing.JTextField ColorDER;
    private javax.swing.JTextField ColorIZQ;
    private javax.swing.JCheckBox Controldiab;
    private javax.swing.JTextField DM;
    private javax.swing.JCheckBox Descalzo;
    private javax.swing.JTextField DespiDER;
    private javax.swing.JTextField DespiIZQ;
    private javax.swing.JTextField DesuDER;
    private javax.swing.JTextField DesuIZQ;
    private javax.swing.JTextField Direc;
    private javax.swing.JTextField DolorDER;
    private javax.swing.JTextField DolorIZQ;
    private javax.swing.JButton Finalizar;
    private javax.swing.JTextField Fnaci;
    private javax.swing.JTextField HTA;
    private javax.swing.JTextField HidratacionDER;
    private javax.swing.JTextField HidratacionIZQ;
    private javax.swing.JTextField InflaDER;
    private javax.swing.JTextField InflaIZQ;
    private javax.swing.JCheckBox Lavpies;
    private javax.swing.JCheckBox LimMovilidad;
    private javax.swing.JTextField LimpDER;
    private javax.swing.JTextField LimpIZQ;
    private javax.swing.JTextField LimpdigDER;
    private javax.swing.JTextField LimpdigIZQ;
    private javax.swing.JTextField Marcapasos;
    private javax.swing.JTextField MaspodDER;
    private javax.swing.JTextField MaspodIZQ;
    private javax.swing.JTextField OlorDER;
    private javax.swing.JTextField OlorIZQ;
    private javax.swing.JTextField OnicDER;
    private javax.swing.JTextField OnicIZQ;
    private javax.swing.JTextField OtroDER;
    private javax.swing.JTextField OtroIZQ;
    private javax.swing.JTextField OtroTraDER;
    private javax.swing.JTextField OtroTraIZQ;
    private javax.swing.JTextArea Otros;
    private javax.swing.JTextField PatoDER;
    private javax.swing.JTextField PatoIZQ;
    private javax.swing.JPanel PodoPanel;
    private javax.swing.JCheckBox Pulsopedido;
    private javax.swing.JTextField ResecDER;
    private javax.swing.JTextField ResecIZQ;
    private javax.swing.JTextField ResecheDER;
    private javax.swing.JTextField ResecheIZQ;
    private javax.swing.JTextField ResechipDER;
    private javax.swing.JTextField ResechipIZQ;
    private javax.swing.JCheckBox Sensivilidad;
    private javax.swing.JTextField TempDER;
    private javax.swing.JTextField TempIZQ;
    private javax.swing.JButton Volver;
    private javax.swing.JCheckBox Watero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private javax.swing.JTextField corre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
